# Generated by Django 5.1.3 on 2025-01-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespitch', '0002_chatsession_session_name_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='message',
        ),
    ]
