# Generated by Django 5.1 on 2025-03-28 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespitch', '0003_remove_bookmark_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='salespitch.chatmessage'),
        ),
    ]
